# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
name: Test image generation

on:
  push:
    paths:
      - 'src/**'
      - 'test/**'

jobs:
  build_images:
    if: github.repository == 'Asahu117/cloud-native-ecommerce-platform'
    uses: ./.github/workflows/component-build-images.yml
